### ISSUE TITLE
[NFT] - Function to batch mint for pre-ordered addresses

### ISSUE THREAD

**Issue by devformatters** [thematters/traveloggers-contracts#13]
Doc is [here](https://paper.dropbox.com/doc/Smart-Contract-BTd2d4ZRBsgaxLXWtLl0PTkfAg-GIDkfXqyQsqjmAc1IRt6f#:uid=293017630347625209147086&h2=Pre-order-@Chen-C).

**Comment by guoliu** [comment]
User will mint NFT for themselves instead: https://github.com/thematters/matters-avatar/issues/39
