### ISSUE TITLE
[NFT] - Deploy contract with upgrade plugin

### ISSUE THREAD

**Issue by guoliu** [thematters/traveloggers-contracts#22]
Ref: https://docs.openzeppelin.com/learn/upgrading-smart-contracts

* Research the extra cost of introducing upgradable proxy
* Research if there are extra limitations down the line
* Implementation

**Comment by Carolusian** [comment]
- [introduced different ways to upgrade smart contracts](https://vomtom.at/upgrade-smart-contracts-on-chain/)
  - via proxy
  - via storage contract
- [upgrading smart contracts using OpenZeppelin's upgrade plugin](https://docs.openzeppelin.com/learn/upgrading-smart-contracts)
